### PR TITLE
add methods for length and size of Row

### PR DESCRIPTION
**Pull request by visr**
Useful for https://github.com/JuliaGeo/Shapefile.jl/issues/50.

### CODE REVIEW

**Comment by quinnj** [comment]
To make this a little more robust, I think we should have `struct Row <: Tables.AbstractRow`. Then we get length, getproperty, getindex, etc. all for free. The other changes needed then is to switch from defining `propertynames`, `getproperty` to defining `Tables.columnnames` and `Tables.getcolumn`. If you're up for that, it'd be a great improvement. I can also do it if you'd rather.

**Comment by visr** [comment]
Ah that sounds good, I wasn't aware of `Tables.AbstractRow`. I'll try it out in a few days.

**Review by quinnj — APPROVED** [review]

**Comment by quinnj** [comment]
@visr , anything else you wanted to add/change here? It LGTM. Should we merge & tag?

**Comment by visr** [comment]
Nope, merge and tag would be great!

**Pull request merged**
