### PR TITLE
fix v0.7.0 deprecation

### PR DESCRIPTION
**Pull request by cchderrick**
I believe this commit cover all deprecations in v0.7.0.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. Can you also update the TravisCI and AppVeyor files to stop testing Julia 0.6 and test 0.7, 1.0 and nightly instead?

**Comment by cchderrick** [comment]
New to CI; something like this in `.travis.yml`?
```
julia:
  - 0.7
  - 1.0
  - nightly
```

What to do for `after_success`? it seems like it need updates; `Pkg.dir(pkgname, paths...)` is deprecated.

**Comment by nalimilan** [comment]
Yes. You can have a look at https://github.com/JuliaData/DataFrames.jl/blob/master/.travis.yml.

**Comment by nalimilan** [comment]
Thanks! I've tagged a release: https://github.com/JuliaLang/METADATA.jl/pull/18436

**Pull request merged**
